name: "CI/CD Pipeline"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # CHECKOUT
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # SETUP
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # BUILD
      - name: Build project
        run: npm run build
      
      # UPLOAD BUILD ARTIFACTS
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
 …
